# Generated by Django 4.2.13 on 2024-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='player',
            field=models.CharField(max_length=100),
        ),
    ]
